<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
		<link type="text/css" rel="stylesheet" href="/css/core.css" />
		<link type="text/css" rel="stylesheet" href="/css/styles.css" />
		<script type="text/javascript" src="/js/jquery.js"></script>
		<script type="text/javascript" src="/js/admin/admin.js"></script>
		    <?php echo $this->headTitle()?>
		    <?php echo $this->headScript()?>
		    <?php echo $this->headStyle()?>
		    <?php echo $this->headLink()?>
	</head>
	<body>
		<div class="wrapper">
			<div class="page">
				<div class="header-container">
					<?php include "inc/admin_header.phtml"  ?>
				</div>
			 	<div class="main-container">
			 		<div id="main">
			 		<?php echo $this->layout()->content ?>
			 		</div>
			 	</div>
			 	
			 	<div class="footer-container">
				 	<div class="footer">
				 	&copy; <?=date('Y');?> Sci-Fi Store LLC. All Rights Reserved.
				 	</div>				
			 	</div>
			</div>
		</div>
	</body>
</html>