<?php

/**
 * Default_Model_Base_Address
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int $billing
 * @property int $shipping
 * @property integer $user_id
 * @property string $name
 * @property string $address
 * @property string $city
 * @property string $state
 * @property string $zip
 * @property string $phone
 * @property datetime $date_created
 * @property datetime $date_updated
 * @property Default_Model_User $User
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Default_Model_Base_Address extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('default__model__address');
        $this->hasColumn('billing', 'int', 1, array(
             'type' => 'int',
             'length' => '1',
             'default' => 0,
             ));
        $this->hasColumn('shipping', 'int', 1, array(
             'type' => 'int',
             'length' => '1',
             'default' => 0,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('address', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('city', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('state', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('zip', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('phone', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('date_created', 'datetime', null, array(
             'type' => 'datetime',
             ));
        $this->hasColumn('date_updated', 'datetime', null, array(
             'type' => 'datetime',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Default_Model_User as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));
    }
}