<?php

/**
 * Default_Model_Base_Role
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property int $default_role
 * @property Doctrine_Collection $Resources
 * @property Doctrine_Collection $Default_Model_RoleResource
 * @property Doctrine_Collection $Default_Model_UserRole
 * @property Doctrine_Collection $Users
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Default_Model_Base_Role extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('default__model__role');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('default_role', 'int', 1, array(
             'type' => 'int',
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Default_Model_Resource as Resources', array(
             'refClass' => 'Default_Model_RoleResource',
             'local' => 'role_id',
             'foreign' => 'resource_id'));

        $this->hasMany('Default_Model_RoleResource', array(
             'local' => 'id',
             'foreign' => 'role_id'));

        $this->hasMany('Default_Model_UserRole', array(
             'local' => 'id',
             'foreign' => 'role_id'));

        $this->hasMany('Default_Model_User as Users', array(
             'refClass' => 'Default_Model_UserRole',
             'local' => 'role_id',
             'foreign' => 'user_id'));
    }
}