<?php

/**
 * Default_Model_Base_RoleResource
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $role_id
 * @property integer $resource_id
 * @property Default_Model_Resource $Resource
 * @property Default_Model_Role $Role
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Default_Model_Base_RoleResource extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('default__model__role_resource');
        $this->hasColumn('role_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('resource_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Default_Model_Resource as Resource', array(
             'local' => 'resource_id',
             'foreign' => 'id'));

        $this->hasOne('Default_Model_Role as Role', array(
             'local' => 'role_id',
             'foreign' => 'id'));
    }
}