<?php

/**
 * Catalog_Model_Base_Category
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $parent_id
 * @property Catalog_Model_Category $Parent
 * @property Doctrine_Collection $Products
 * @property Doctrine_Collection $Catalog_Model_Category
 * @property Doctrine_Collection $Catalog_Model_ProductCategory
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Catalog_Model_Base_Category extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('catalog__model__category');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('parent_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Catalog_Model_Category as Parent', array(
             'local' => 'parent_id',
             'foreign' => 'id'));

        $this->hasMany('Catalog_Model_Product as Products', array(
             'refClass' => 'Catalog_Model_ProductCategory',
             'local' => 'category_id',
             'foreign' => 'product_id'));

        $this->hasMany('Catalog_Model_Category', array(
             'local' => 'id',
             'foreign' => 'parent_id'));

        $this->hasMany('Catalog_Model_ProductCategory', array(
             'local' => 'id',
             'foreign' => 'category_id'));
    }
}