<?php

/**
 * Catalog_Model_Base_ProductCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $product_id
 * @property integer $category_id
 * @property Catalog_Model_Product $Product
 * @property Catalog_Model_Category $Category
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Catalog_Model_Base_ProductCategory extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('catalog__model__product_category');
        $this->hasColumn('product_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Catalog_Model_Product as Product', array(
             'local' => 'product_id',
             'foreign' => 'id'));

        $this->hasOne('Catalog_Model_Category as Category', array(
             'local' => 'category_id',
             'foreign' => 'id'));
    }
}