			<div class="header">
				<div class="left header-title">Sci-Fi Store Admin</div>
				<div id="loggedInAs" class="right">
					<?php echo $this->loggedInAs(); ?>
				</div>
				<div class="clear"></div>
				<div class="">
					<ul id="navbar">
						<li><a href="/admin">Dashboard</a></li>
						<li><a href="/admin/sales">Sales</a></li>
						<li><a href="/admin/catalog">Catalog</a>
						</li>
						<li><a href="/admin/customer">Customers</a></li>
						<li><a href="/admin/reports">Reports</a></li>
						<li><a href="/admin/system">System</a></li>
					</ul>
				</div>	
			</div>